// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAK6AVOrVC3x6yENlrutpseLbWc__o3Ipk',
    appId: '1:240191954451:web:19e14e02b055fba359a9e6',
    messagingSenderId: '240191954451',
    projectId: 'flutter-test-379c7',
    authDomain: 'flutter-test-379c7.firebaseapp.com',
    storageBucket: 'flutter-test-379c7.firebasestorage.app',
    measurementId: 'G-HZCMPBN9GG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLPef1CnpfBU-Z80UYn7AYwUgTIi9193s',
    appId: '1:240191954451:android:4c41759761ee659b59a9e6',
    messagingSenderId: '240191954451',
    projectId: 'flutter-test-379c7',
    storageBucket: 'flutter-test-379c7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoSmamHL7nK6-PRnEsDSwoieXKHQf8Ypo',
    appId: '1:240191954451:ios:cf747c302119f5a559a9e6',
    messagingSenderId: '240191954451',
    projectId: 'flutter-test-379c7',
    storageBucket: 'flutter-test-379c7.firebasestorage.app',
    iosBundleId: 'com.example.firebaseSFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoSmamHL7nK6-PRnEsDSwoieXKHQf8Ypo',
    appId: '1:240191954451:ios:cf747c302119f5a559a9e6',
    messagingSenderId: '240191954451',
    projectId: 'flutter-test-379c7',
    storageBucket: 'flutter-test-379c7.firebasestorage.app',
    iosBundleId: 'com.example.firebaseSFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAK6AVOrVC3x6yENlrutpseLbWc__o3Ipk',
    appId: '1:240191954451:web:2002deeae34a8d5859a9e6',
    messagingSenderId: '240191954451',
    projectId: 'flutter-test-379c7',
    authDomain: 'flutter-test-379c7.firebaseapp.com',
    storageBucket: 'flutter-test-379c7.firebasestorage.app',
    measurementId: 'G-VMXTDR8QDG',
  );
}
